name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: 'temurin'

            - name: Build with Maven
              run: mvn --batch-mode -Pdefault,coverage install

            - name: Run SonarCloud analysis
              run: >
                  mvn --batch-mode -DskipTests sonar:sonar
                  -Dsonar.host.url=https://sonarcloud.io
                  -Dsonar.organization=farao-community
                  -Dsonar.projectKey=farao-community_gridcapa-interruption-server
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Build and publish Docker image
              if: github.ref == 'refs/heads/main'
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                name: farao/gridcapa-interruption-server
                username: farao
                password: ${{ secrets.DOCKERHUB_TOKEN }}
